import urllib.request
import urllib.parse
import json
import time

BASE_URL = "http://127.0.0.1:8000"

def make_request(path, method="GET", data=None, token=None):
    url = f"{BASE_URL}{path}"
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
        
    encoded_data = None
    if data:
        if isinstance(data, dict):
            encoded_data = json.dumps(data).encode("utf-8")
        else:
            encoded_data = data
            
    req = urllib.request.Request(
        url,
        data=encoded_data,
        headers=headers,
        method=method
    )
    
    try:
        with urllib.request.urlopen(req) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        error_body = e.read().decode("utf-8")
        print(f"[-] HTTP Error: {e.code} - {error_body}")
        raise e

def test_full_workflow():
    print("[+] --- STARTING FULL END-TO-END WORKFLOW TEST ---")
    
    # 1. Register a Landowner (Owner)
    print("\n[1] Registering Landowner...")
    owner_email = f"owner_{int(time.time())}@wetlands.org"
    owner_wallet = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC" # Hardhat Account #2
    reg_owner = make_request("/auth/register", "POST", {
        "email": owner_email,
        "password": "ownerpass123",
        "role": "owner",
        "wallet_address": owner_wallet
    })
    print(f"[SUCCESS] Registered Owner ID: {reg_owner['id']}")
    
    # 2. Login as Landowner
    print("\n[2] Logging in as Landowner...")
    login_data = urllib.parse.urlencode({
        "username": owner_email,
        "password": "ownerpass123"
    }).encode("utf-8")
    
    # Needs to bypass application/json header for OAuth2 form
    headers = {"Content-Type": "application/x-www-form-urlencoded"}
    req = urllib.request.Request(f"{BASE_URL}/auth/login", data=login_data, headers=headers, method="POST")
    with urllib.request.urlopen(req) as response:
        login_res = json.loads(response.read().decode("utf-8"))
    owner_token = login_res["access_token"]
    print("[SUCCESS] Got Owner JWT Token")

    # 3. Submit a project (mangrove polygon coordinates in Sundarbans)
    print("\n[3] Submitting Mangrove Project...")
    project_payload = {
        "name": "Sundarbans Delta Mangrove A",
        "ecosystem_type": "mangrove",
        "polygon_geojson": {
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [[
                    [88.39, 21.82],
                    [88.42, 21.82],
                    [88.42, 21.85],
                    [88.39, 21.85],
                    [88.39, 21.82]
                ]]
            }
        }
    }
    
    project = make_request("/projects", "POST", project_payload, token=owner_token)
    project_id = project["id"]
    print(f"[SUCCESS] Project submitted successfully. ID: {project_id}")
    print(f"          Initial status: {project['status']}")
    
    # Let satellite MRV process and calculate estimates
    # (Since we run in sync mode when delay fails, or wait for tasks)
    print("\n[4] Fetching Carbon Estimates generated by Satellite MRV...")
    time.sleep(2) # Give a small window
    proj_details = make_request(f"/projects/{project_id}")
    print(f"          Status after Remote Sensing: {proj_details['status']}")
    
    carbon_estimates = proj_details.get("carbon_estimates", [])
    if carbon_estimates:
        credits_val = carbon_estimates[0]["credits"]
        print(f"[SUCCESS] Calculated Credits: {credits_val} BCC (tCO2e)")
    else:
        print("[-] Error: Carbon estimates were not generated!")
        return

    # 4. Register a Verifier
    print("\n[5] Registering Verifier...")
    verifier_email = f"verifier_{int(time.time())}@audit.org"
    verifier_wallet = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8" # Hardhat Account #1
    reg_verifier = make_request("/auth/register", "POST", {
        "email": verifier_email,
        "password": "verifierpass123",
        "role": "verifier",
        "wallet_address": verifier_wallet
    })
    print(f"[SUCCESS] Registered Verifier ID: {reg_verifier['id']}")
    
    # 5. Login as Verifier
    print("\n[6] Logging in as Verifier...")
    login_data = urllib.parse.urlencode({
        "username": verifier_email,
        "password": "verifierpass123"
    }).encode("utf-8")
    req = urllib.request.Request(f"{BASE_URL}/auth/login", data=login_data, headers=headers, method="POST")
    with urllib.request.urlopen(req) as response:
        login_res = json.loads(response.read().decode("utf-8"))
    verifier_token = login_res["access_token"]
    print("[SUCCESS] Got Verifier JWT Token")

    # 6. Approve project to trigger smart contract minting
    print("\n[7] Verifying and Approving Project (Minting Credits)...")
    approval_res = make_request(
        f"/verification/{project_id}/approve",
        "POST",
        {
            "decision": "approved",
            "comment": "NDVI baseline matches Sentinel-2 observations. Approved for credit minting."
        },
        token=verifier_token
    )
    print(f"[SUCCESS] Project status updated: {approval_res['status']}")
    
    # 7. Check database blockchain transaction record
    time.sleep(2)
    updated_project = make_request(f"/projects/{project_id}")
    print("\n[8] Verifying Blockchain Ledger Record in Database...")
    for tx in updated_project.get("blockchain_transactions", []):
        print(f"[SUCCESS] On-chain transaction found! Action: {tx['action']}, Amount: {tx['amount']} BCC")
        print(f"          Transaction Hash: {tx['tx_hash']}")
        
    print("\n[SUCCESS] FULL END-TO-END REGISTRATION, SATELLITE MRV, AND ON-CHAIN MINTING SUCCESSFUL!")

if __name__ == "__main__":
    test_full_workflow()
